/**
 * WCC Membership Management System - Realistic Mock Dataset
 * Exactly aligned with PokkaVau/WCC_MemberShip_Form-V2-
 * 26 Columns: Timestamp, Name (BN), Name (EN), DOB, Father, Mother, NID/BRN, Blood,
 * Mobile, Email, Present Add, Permanent Add, Currently Studying, Class/Year,
 * Current Institution, Last Public Exam, Public Exam Result, Last Qualification,
 * Last Result, Last Institution, Profession, Workplace, Membership, Wing, Reason, Photo URL
 */

const MOCK_MEMBERS_RAW = [
  {
    "Member ID": "WCC-2026-0001",
    "Timestamp": "2026-01-10 10:30:15",
    "Name (BN)": "তানভীর আহমেদ চৌধুরী",
    "Name (EN)": "TANVIR AHMED CHOWDHURY",
    "DOB": "1998-04-15",
    "Father": "মোঃ রফিকুল ইসলাম চৌধুরী",
    "Mother": "নাসিমা আক্তার",
    "NID/BRN": "19982692015000101",
    "Blood": "বি+",
    "Mobile": "01711234567",
    "Email": "tanvir.chowdhury@example.com",
    "Present Add": "বাসা নং ১২, কলেজ রোড, ঝালকাঠি সদর, ঝালকাঠি",
    "Permanent Add": "গ্রাম: বাউকাঠি, ডাকঘর: ঝালকাঠি, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "5.00",
    "Last Qualification": "Bachelor / Honours",
    "Last Result": "3.78",
    "Last Institution": "ঢাকা বিশ্ববিদ্যালয়",
    "Profession": "সফটওয়্যার ইঞ্জিনিয়ার",
    "Workplace": "টেক সল্যুশনস লিমিটেড, কারওয়ান বাজার, ঢাকা",
    "Membership": "Lifetime",
    "Wing": "শিক্ষা উইং",
    "Reason": "ঝালকাঠির পিছিয়ে পড়া শিক্ষার্থীদের প্রযুক্তি ও উচ্চশিক্ষায় ক্যারিয়ার গাইডলাইন প্রদান করা।",
    "Photo URL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0002",
    "Timestamp": "2026-01-12 14:20:00",
    "Name (BN)": "নুসরাত জাহান মীম",
    "Name (EN)": "NUSRAT JAHAN MIM",
    "DOB": "2003-08-22",
    "Father": "আব্দুল জলিল আকন",
    "Mother": "রোকেয়া বেগম",
    "NID/BRN": "20032692015000102",
    "Blood": "ও+",
    "Mobile": "01812987654",
    "Email": "nusrat.mim@example.com",
    "Present Add": "পশ্চিম চাঁদকাঠি, ঝালকাঠি পৌরসভা, ঝালকাঠি",
    "Permanent Add": "পশ্চিম চাঁদকাঠি, ঝালকাঠি পৌরসভা, ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "৩য় বর্ষ",
    "Current Institution": "বরিশাল বিশ্ববিদ্যালয়",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.92",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "বরিশাল বিশ্ববিদ্যালয়",
    "Membership": "General",
    "Wing": "স্বাস্থ্য উইং",
    "Reason": "ঝালকাঠির গ্রামীণ নারীদের মাঝে স্বাস্থ্য সচেতনতা ও রক্তদান কার্যক্রমে সক্রিয় ভূমিকা পালন করতে চাই।",
    "Photo URL": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0003",
    "Timestamp": "2026-01-15 11:15:30",
    "Name (BN)": "মোঃ নাজমুল হাসান",
    "Name (EN)": "MD. NAZMUL HASAN",
    "DOB": "1995-11-05",
    "Father": "মোঃ মোখলেছুর রহমান",
    "Mother": "ফাতেমা জোহরা",
    "NID/BRN": "19952692015000103",
    "Blood": "এ+",
    "Mobile": "01913456789",
    "Email": "nazmul.hasan@example.com",
    "Present Add": "মেইন রোড, রাজাপুর বাজার, রাজাপুর, ঝালকাঠি",
    "Permanent Add": "গ্রাম: পুটিয়াখালি, ডাকঘর: রাজাপুর, উপজেলা: রাজাপুর, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.80",
    "Last Qualification": "Masters",
    "Last Result": "3.65",
    "Last Institution": "সরকারি ব্রজমোহন (বিএম) কলেজ, বরিশাল",
    "Profession": "শিক্ষক",
    "Workplace": "রাজাপুর পাইলট বালিকা উচ্চ বিদ্যালয়",
    "Membership": "Lifetime",
    "Wing": "সাংস্কৃতিক উইং",
    "Reason": "স্থানীয় তরুণ প্রজন্মকে মাদক ও অপরাধ থেকে দূরে রেখে শিল্প ও সংস্কৃতি চর্চায় যুক্ত করা।",
    "Photo URL": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0004",
    "Timestamp": "2026-01-18 16:45:10",
    "Name (BN)": "সাদিয়া আফরিন রিমা",
    "Name (EN)": "SADIA AFRIN RIMA",
    "DOB": "2004-02-14",
    "Father": "মোঃ শাহজাহান হাওলাদার",
    "Mother": "সুলতানা রাজিয়া",
    "NID/BRN": "20042692015000104",
    "Blood": "এবি+",
    "Mobile": "01722334455",
    "Email": "sadia.rima@example.com",
    "Present Add": "নলছিটি পৌর এলাকা, নলছিটি, ঝালকাঠি",
    "Permanent Add": "গ্রাম: কুলকাঠি, উপজেলা: নলছিটি, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "২য় বর্ষ",
    "Current Institution": "ঝালকাঠি সরকারি কলেজ",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "5.00",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "ঝালকাঠি সরকারি কলেজ",
    "Membership": "General",
    "Wing": "পরিবেশ সংরক্ষণ উইং",
    "Reason": "সুগন্ধা নদী রক্ষা, পলিথিন বর্জন ও বৃক্ষরোপণ কর্মসূচির মাধ্যমে ঝালকাঠির পরিবেশ রক্ষা করা।",
    "Photo URL": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0005",
    "Timestamp": "2026-01-22 09:30:00",
    "Name (BN)": "কাজী আরিফুল ইসলাম",
    "Name (EN)": "KAZI ARIFUL ISLAM",
    "DOB": "1999-07-30",
    "Father": "কাজী মোজাফফর হোসেন",
    "Mother": "আনোয়ারা বেগম",
    "NID/BRN": "19992692015000105",
    "Blood": "ও-",
    "Mobile": "01633445566",
    "Email": "ariful.islam@example.com",
    "Present Add": "কাঠালিয়া বাজার রোড, কাঠালিয়া, ঝালকাঠি",
    "Permanent Add": "গ্রাম: আওরাবুনিয়া, উপজেলা: কাঠালিয়া, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "Diploma in Engineering",
    "Public Exam Result": "3.85",
    "Last Qualification": "Diploma",
    "Last Result": "3.85",
    "Last Institution": "বরিশাল পলিটেকনিক ইনস্টিটিউট",
    "Profession": "উপ-সহকারী প্রকৌশলী",
    "Workplace": "স্থানীয় সরকার প্রকৌশল অধিদপ্তর (এলজিইডি)",
    "Membership": "General",
    "Wing": "খেলাধুলা উইং",
    "Reason": "গ্রামাঞ্চলের যুবকদের ক্রীড়া প্রতিযোগিতা আয়োজন ও মানসিক বিকাশে সহযোগিতা করা।",
    "Photo URL": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0006",
    "Timestamp": "2026-01-25 12:10:45",
    "Name (BN)": "ফারজানা ইয়াসমিন সোনিয়া",
    "Name (EN)": "FARZANA YASMIN SONIA",
    "DOB": "2001-12-10",
    "Father": "মোঃ ফারুক হোসেন মল্লিক",
    "Mother": "পারভীন আক্তার",
    "NID/BRN": "20012692015000106",
    "Blood": "বি-",
    "Mobile": "01744556677",
    "Email": "farzana.sonia@example.com",
    "Present Add": "স্টেডিয়াম রোড, ঝালকাঠি সদর",
    "Permanent Add": "গ্রাম: গাবখান, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "৪র্থ বর্ষ",
    "Current Institution": "সরকারি বিএম কলেজ, বরিশাল",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.85",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "সরকারি বিএম কলেজ",
    "Membership": "General",
    "Wing": "শিক্ষা উইং",
    "Reason": "দরিদ্র শিশুদের জন্য ফ্রিতে বই বিতরণ এবং মৌলিক শিক্ষা প্রদান কর্মসূচিতে অংশ নেওয়া।",
    "Photo URL": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250",
    "Status": "Pending"
  },
  {
    "Member ID": "WCC-2026-0007",
    "Timestamp": "2026-01-28 15:40:20",
    "Name (BN)": "মোঃ মাহিনুর রহমান",
    "Name (EN)": "MD. MAHINUR RAHMAN",
    "DOB": "1997-03-25",
    "Father": "মোঃ আনিসুর রহমান",
    "Mother": "জাহানারা বেগম",
    "NID/BRN": "19972692015000107",
    "Blood": "এ+",
    "Mobile": "01855667788",
    "Email": "mahinur.rahman@example.com",
    "Present Add": "কলেজ মোড়, নলছিটি, ঝালকাঠি",
    "Permanent Add": "গ্রাম: রানাপাশা, উপজেলা: নলছিটি, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.75",
    "Last Qualification": "Bachelor / Honours",
    "Last Result": "3.55",
    "Last Institution": "পটুয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "Profession": "কৃষি কর্মকর্তা",
    "Workplace": "কৃষি সম্প্রসারণ অধিদপ্তর, ঝালকাঠি",
    "Membership": "Lifetime",
    "Wing": "পরিবেশ সংরক্ষণ উইং",
    "Reason": "প্রাকৃতিক কৃষি ও বৃক্ষরোপণের মাধ্যমে প্রাকৃতিক ভারসাম্য রক্ষার আন্দোলনে যুক্ত থাকা।",
    "Photo URL": "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0008",
    "Timestamp": "2026-02-02 11:05:00",
    "Name (BN)": "সাবরিনা মোস্তফা নিশি",
    "Name (EN)": "SABRINA MOSTAFA NISHI",
    "DOB": "2005-09-18",
    "Father": "গোলাম মোস্তফা সিকদার",
    "Mother": "লুৎফুন্নাহার",
    "NID/BRN": "20052692015000108",
    "Blood": "ও+",
    "Mobile": "01966778899",
    "Email": "sabrina.nishi@example.com",
    "Present Add": "কৃষ্ণকাঠি, ঝালকাঠি সদর",
    "Permanent Add": "কৃষ্ণকাঠি, ঝালকাঠি সদর, ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "দ্বাদশ শ্রেণি",
    "Current Institution": "ঝালকাঠি সরকারি মহিলা কলেজ",
    "Last Public Exam": "SSC / সমমান",
    "Public Exam Result": "5.00",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "ঝালকাঠি সরকারি মহিলা কলেজ",
    "Membership": "General",
    "Wing": "সাংস্কৃতিক উইং",
    "Reason": "বিতর্ক, ক্যালিগ্রাফি ও আবৃত্তি কর্মশালার মাধ্যমে মেধা বিকাশে নেতৃত্ব দেওয়া।",
    "Photo URL": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0009",
    "Timestamp": "2026-02-05 17:22:15",
    "Name (BN)": "ড. মোস্তফা কামাল",
    "Name (EN)": "DR. MOSTAFA KAMAL",
    "DOB": "1988-06-12",
    "Father": "মরহুম আলহাজ্ব কামাল উদ্দিন",
    "Mother": "হাফিজা খাতুন",
    "NID/BRN": "19882692015000109",
    "Blood": "এবি-",
    "Mobile": "01777889900",
    "Email": "mostafa.kamal@example.com",
    "Present Add": "সদর হাসপাতাল রোড, ঝালকাঠি",
    "Permanent Add": "গ্রাম: রূপসী, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "5.00",
    "Last Qualification": "Masters",
    "Last Result": "ফার্স্ট ক্লাস",
    "Last Institution": "শেরে বাংলা মেডিকেল কলেজ, বরিশাল",
    "Profession": "চিকিৎসক (মেডিকেল অফিসার)",
    "Workplace": "ঝালকাঠি ২৫০ শয্যা বিশিষ্ট জেলা হাসপাতাল",
    "Membership": "Lifetime",
    "Wing": "স্বাস্থ্য উইং",
    "Reason": "বিনামূল্যে চিকিৎসা ক্যাম্প, চক্ষু পরীক্ষা ও জরুরি রক্ত সহায়তা কার্যক্রমে সেবা দেওয়া।",
    "Photo URL": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0010",
    "Timestamp": "2026-02-08 14:15:30",
    "Name (BN)": "মোঃ সাইদুর রহমান সাঈদ",
    "Name (EN)": "MD. SAYEDUR RAHMAN SAYEED",
    "DOB": "2002-05-20",
    "Father": "মোঃ হাবিবুর রহমান",
    "Mother": "সালেহা বেগম",
    "NID/BRN": "20022692015000110",
    "Blood": "এ+",
    "Mobile": "01688990011",
    "Email": "sayedur.sayeed@example.com",
    "Present Add": "কাঠালিয়া রোড, রাজাপুর, ঝালকাঠি",
    "Permanent Add": "গ্রাম: শুক্তাগড়, উপজেলা: রাজাপুর, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "১ম বর্ষ",
    "Current Institution": "বরিশাল বিশ্ববিদ্যালয়",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.90",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "বরিশাল বিশ্ববিদ্যালয়",
    "Membership": "General",
    "Wing": "খেলাধুলা উইং",
    "Reason": "ফুটবল ও ক্রিকেট টুর্নামেন্ট আয়োজন করে যুবসমাজকে গঠনমূলক কাজে অনুপ্রাণিত করা।",
    "Photo URL": "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250",
    "Status": "Pending"
  },
  {
    "Member ID": "WCC-2026-0011",
    "Timestamp": "2026-02-12 10:00:00",
    "Name (BN)": "তানিয়া আক্তার বৃষ্টি",
    "Name (EN)": "TANIA AKTER BRISTY",
    "DOB": "2000-10-08",
    "Father": "মোঃ দেলোয়ার হোসেন",
    "Mother": "মরিয়ম আক্তার",
    "NID/BRN": "20002692015000111",
    "Blood": "বি+",
    "Mobile": "01799001122",
    "Email": "tania.bristy@example.com",
    "Present Add": "নলছিটি লঞ্চঘাট রোড, নলছিটি, ঝালকাঠি",
    "Permanent Add": "নলছিটি লঞ্চঘাট রোড, নলছিটি, ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "Masters",
    "Current Institution": "ঢাকা বিশ্ববিদ্যালয়",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "5.00",
    "Last Qualification": "Bachelor / Honours",
    "Last Result": "3.82",
    "Last Institution": "ঢাকা বিশ্ববিদ্যালয়",
    "Profession": "শিক্ষার্থী",
    "Workplace": "ঢাকা বিশ্ববিদ্যালয়",
    "Membership": "General",
    "Wing": "শিক্ষা উইং",
    "Reason": "নারী শিক্ষা বৃদ্ধি ও বাল্যবিবাহ রোধে মাঠপর্যায়ে সামাজিক ক্যাম্পেইন পরিচালনা করা।",
    "Photo URL": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0012",
    "Timestamp": "2026-02-15 13:45:00",
    "Name (BN)": "মোঃ রিয়াদুল ইসলাম",
    "Name (EN)": "MD. RIYADUL ISLAM",
    "DOB": "1994-01-17",
    "Father": "নুরুল ইসলাম ফরাজী",
    "Mother": "হাসিনা মমতাজ",
    "NID/BRN": "19942692015000112",
    "Blood": "ও+",
    "Mobile": "01511223344",
    "Email": "riyadul.islam@example.com",
    "Present Add": "প্রেস ক্লাব রোড, ঝালকাঠি সদর",
    "Permanent Add": "গ্রাম: কীর্তিপাশা, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.60",
    "Last Qualification": "Bachelor / Honours",
    "Last Result": "3.40",
    "Last Institution": "জাতীয় বিশ্ববিদ্যালয়",
    "Profession": "সাংবাদিক",
    "Workplace": "দৈনিক প্রথম আলো (জেলা প্রতিনিধি)",
    "Membership": "Lifetime",
    "Wing": "সাংস্কৃতিক উইং",
    "Reason": "ঝালকাঠির ঐতিহাসিক পেয়ারা বাগান ও নদীমাতৃক ঐতিহ্য দেশব্যাপী তুলে ধরা।",
    "Photo URL": "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0013",
    "Timestamp": "2026-02-18 16:30:00",
    "Name (BN)": "নাফিসা বিনতে নাজের",
    "Name (EN)": "NAFISA BINTE NAZER",
    "DOB": "2006-03-05",
    "Father": "নাজের আহমেদ খান",
    "Mother": "নাজমা বেগম",
    "NID/BRN": "20062692015000113",
    "Blood": "এ-",
    "Mobile": "01722446688",
    "Email": "nafisa.nazer@example.com",
    "Present Add": "থানা রোড, রাজাপুর, ঝালকাঠি",
    "Permanent Add": "থানা রোড, রাজাপুর, ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "একাদশ শ্রেণি",
    "Current Institution": "রাজাপুর ডিগ্রি কলেজ",
    "Last Public Exam": "SSC / সমমান",
    "Public Exam Result": "5.00",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "রাজাপুর ডিগ্রি কলেজ",
    "Membership": "General",
    "Wing": "পরিবেশ সংরক্ষণ উইং",
    "Reason": "বিদ্যালয়ে পরিচ্ছন্নতা অভিযান ও বনায়ন ক্যাম্পেইনে সক্রিয় অংশগ্রহণ করতে চাই।",
    "Photo URL": "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0014",
    "Timestamp": "2026-02-22 09:15:00",
    "Name (BN)": "কাজী তানজিল আহমেদ",
    "Name (EN)": "KAZI TANZIL AHMED",
    "DOB": "1992-08-14",
    "Father": "কাজী আবুল বাশার",
    "Mother": "শিরিন আক্তার",
    "NID/BRN": "19922692015000114",
    "Blood": "বি+",
    "Mobile": "01833557799",
    "Email": "tanzil.ahmed@example.com",
    "Present Add": "কাঠালিয়া সদর, কাঠালিয়া, ঝালকাঠি",
    "Permanent Add": "গ্রাম: চেঁচরীরামপুর, উপজেলা: কাঠালিয়া, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.50",
    "Last Qualification": "Masters",
    "Last Result": "3.50",
    "Last Institution": "ঢাকা কলেজ",
    "Profession": "ব্যবসায়ী",
    "Workplace": "মেসার্স তানজিল ট্রেডার্স, কাঠালিয়া",
    "Membership": "Lifetime",
    "Wing": "স্বাস্থ্য উইং",
    "Reason": "প্রাকৃতিক দুর্যোগ ও বন্যার সময় উপকূলীয় মানুষের কাছে জরুরি খাদ্য ও ওষুধ পৌঁছে দেওয়া।",
    "Photo URL": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0015",
    "Timestamp": "2026-02-25 11:50:00",
    "Name (BN)": "শাহরিয়ার হাসান শাকিল",
    "Name (EN)": "SHAHRIAR HASAN SHAKIL",
    "DOB": "2003-11-28",
    "Father": "মোঃ জাকির হোসেন",
    "Mother": "রেহানা পারভীন",
    "NID/BRN": "20032692015000115",
    "Blood": "এবি+",
    "Mobile": "01944668800",
    "Email": "shahriar.shakil@example.com",
    "Present Add": "কৃষ্ণকাঠি, ঝালকাঠি সদর",
    "Permanent Add": "গ্রাম: বিনয়কাঠি, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "২য় বর্ষ",
    "Current Institution": "পটুয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.95",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "পটুয়াখালী বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়",
    "Membership": "General",
    "Wing": "শিক্ষা উইং",
    "Reason": "কম্পিউটার সাক্ষরতা ও সাইবার সিকিউরিটি বিষয়ক সচেতনতামূলক ক্যাম্পেইন পরিচালনা করা।",
    "Photo URL": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0016",
    "Timestamp": "2026-03-01 14:30:00",
    "Name (BN)": "মরিয়ম জামিলা",
    "Name (EN)": "MARIAM JAMILA",
    "DOB": "1996-04-19",
    "Father": "মোঃ সিরাজুল ইসলাম",
    "Mother": "খালেদা আক্তার",
    "NID/BRN": "19962692015000116",
    "Blood": "ও+",
    "Mobile": "01755779911",
    "Email": "mariam.jamila@example.com",
    "Present Add": "উপজেলা পরিষদ চত্বর, নলছিটি, ঝালকাঠি",
    "Permanent Add": "গ্রাম: ভৈরবপাশা, উপজেলা: নলছিটি, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.80",
    "Last Qualification": "Bachelor / Honours",
    "Last Result": "3.60",
    "Last Institution": "বরিশাল বিশ্ববিদ্যালয়",
    "Profession": "সমাজকর্মী",
    "Workplace": "ব্র্যাক (BRAC) এনজিও",
    "Membership": "General",
    "Wing": "স্বাস্থ্য উইং",
    "Reason": "প্রান্তিক জনগোষ্ঠীর মা ও শিশুর পুষ্টি নিশ্চিত করতে সচেতনতামূলক প্রকল্প বাস্তবায়ন।",
    "Photo URL": "https://images.unsplash.com/photo-1548142813-c348350df52b?auto=format&fit=crop&q=80&w=250",
    "Status": "Inactive"
  },
  {
    "Member ID": "WCC-2026-0017",
    "Timestamp": "2026-03-04 10:10:00",
    "Name (BN)": "মোঃ আল ইমরান",
    "Name (EN)": "MD. AL IMRAN",
    "DOB": "2004-07-02",
    "Father": "মোঃ ইউনুস আলী",
    "Mother": "মমতাজ বেগম",
    "NID/BRN": "20042692015000117",
    "Blood": "এ+",
    "Mobile": "01666880022",
    "Email": "al.imran@example.com",
    "Present Add": "ঝালকাঠি সরকারি কলেজ রোড, ঝালকাঠি",
    "Permanent Add": "গ্রাম: ধানসিঁড়ি, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "১ম বর্ষ",
    "Current Institution": "ঝালকাঠি সরকারি কলেজ",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.70",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "ঝালকাঠি সরকারি কলেজ",
    "Membership": "General",
    "Wing": "খেলাধুলা উইং",
    "Reason": "জীবনানন্দ দাশের স্মৃতিধন্য ধানসিঁড়ি নদী রক্ষায় যুবকদের সমন্বয়ে সামাজিক আন্দোলন গড়ে তোলা।",
    "Photo URL": "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0018",
    "Timestamp": "2026-03-08 16:00:00",
    "Name (BN)": "ইসরাত জাহান ইতি",
    "Name (EN)": "ISRAT JAHAN ITI",
    "DOB": "2001-01-25",
    "Father": "মোঃ জাহাঙ্গীর আলম",
    "Mother": "রওশন আরা বেগম",
    "NID/BRN": "20012692015000118",
    "Blood": "বি-",
    "Mobile": "01777991133",
    "Email": "israt.iti@example.com",
    "Present Add": "নলছিটি শহর, ঝালকাঠি",
    "Permanent Add": "গ্রাম: কুশঙ্গল, উপজেলা: নলছিটি, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "৩য় বর্ষ",
    "Current Institution": "সরকারি ব্রজমোহন কলেজ",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.88",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "সরকারি ব্রজমোহন কলেজ",
    "Membership": "General",
    "Wing": "সাংস্কৃতিক উইং",
    "Reason": "সাহিত্য প্রতিযোগিতা ও দেয়ালিকা প্রকাশের মাধ্যমে নতুন লেখক সৃষ্টি করা।",
    "Photo URL": "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=250",
    "Status": "Pending"
  },
  {
    "Member ID": "WCC-2026-0019",
    "Timestamp": "2026-03-12 11:20:00",
    "Name (BN)": "মোঃ তৌহিদুল ইসলাম বাপ্পি",
    "Name (EN)": "MD. TOUHIDUL ISLAM BAPPI",
    "DOB": "1993-09-09",
    "Father": "মোঃ নূর মোহাম্মদ",
    "Mother": "আমেনা বেগম",
    "NID/BRN": "19932692015000119",
    "Blood": "ও-",
    "Mobile": "01888002244",
    "Email": "touhidul.bappi@example.com",
    "Present Add": "সদর রোড, ঝালকাঠি পৌরসভা",
    "Permanent Add": "গ্রাম: বাউকাঠি, উপজেলা: ঝালকাঠি সদর, জেলা: ঝালকাঠি",
    "Currently Studying": "না",
    "Class/Year": "",
    "Current Institution": "",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.40",
    "Last Qualification": "Bachelor / Honours",
    "Last Result": "3.35",
    "Last Institution": "বরিশাল সরকারি কলেজ",
    "Profession": "ব্যাংক কর্মকর্তা",
    "Workplace": "সোনালী ব্যাংক লিমিটেড, ঝালকাঠি শাখা",
    "Membership": "Lifetime",
    "Wing": "শিক্ষা উইং",
    "Reason": "ঝালকাঠির মেধাবী কিন্তু অসচ্ছল শিক্ষার্থীদের জন্য শিক্ষাবৃত্তি ফান্ড পরিচালনা করা।",
    "Photo URL": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  },
  {
    "Member ID": "WCC-2026-0020",
    "Timestamp": "2026-03-15 15:10:00",
    "Name (BN)": "সুমি আক্তার",
    "Name (EN)": "SUMI AKTER",
    "DOB": "2003-04-04",
    "Father": "মোঃ খলিলুর রহমান",
    "Mother": "মর্জিনা বেগম",
    "NID/BRN": "20032692015000120",
    "Blood": "এ+",
    "Mobile": "01999113355",
    "Email": "sumi.akter@example.com",
    "Present Add": "রাজাপুর বাজার, রাজাপুর, ঝালকাঠি",
    "Permanent Add": "গ্রাম: মঠবাড়ি, উপজেলা: রাজাপুর, জেলা: ঝালকাঠি",
    "Currently Studying": "হ্যাঁ",
    "Class/Year": "২য় বর্ষ",
    "Current Institution": "ঝালকাঠি সরকারি কলেজ",
    "Last Public Exam": "HSC / সমমান",
    "Public Exam Result": "4.75",
    "Last Qualification": "",
    "Last Result": "",
    "Last Institution": "",
    "Profession": "শিক্ষার্থী",
    "Workplace": "ঝালকাঠি সরকারি কলেজ",
    "Membership": "General",
    "Wing": "পরিবেশ সংরক্ষণ উইং",
    "Reason": "বৃক্ষরোপণ ও উপকূলীয় বাঁধ সংরক্ষণে স্বেচ্ছাসেবী কার্যক্রমে অংশ নেওয়া।",
    "Photo URL": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250",
    "Status": "Active"
  }
];

/**
 * Returns mock members matching the exact 26 Google Sheet columns
 */
function getMockMembers() {
  return MOCK_MEMBERS_RAW.map(m => ({ ...m }));
}
